### ISSUE TITLE
Old icons still available?

### ISSUE THREAD

**Issue by Torbet** [jasonlong/iterm2-icons#4]
Would it be possible to include the old set of icons in here swell? I can't find them anywhere and prefer them to Big Sur's new icon shape! many thanks

**Comment by jasonlong** [comment]
@Torbet I probably won't keep them in the most current repo listings, but – Git to the rescue! – here's a link to an older version of the repo where you will always be able to grab them:

https://github.com/jasonlong/iterm2-icons/tree/82a5e64539ccc2793c5762d02edbdf668bcdb4c5
