### ISSUE TITLE
Why is there a creepy eye?

### ISSUE THREAD

**Issue by romanr** [jasonlong/iterm2-icons#7]
Is it a secret sign of some kind? Conspiracy?

![image](https://github.com/jasonlong/iterm2-icons/assets/329079/57148050-8133-410f-8f6f-800af0bb53de)
![image](https://github.com/jasonlong/iterm2-icons/assets/329079/a6d8edcb-d04b-4d8c-b6d1-1dc5363042f8)

**Comment by jasonlong** [comment]
lol how have I never noticed that??

I think I need to leave it for the mystery of it all
