### ISSUE TITLE
Nit: size is a tiny bit off from other MacOS icons

### ISSUE THREAD

**Issue by scosman** [jasonlong/iterm2-icons#8]
Thanks for the awesome icons.

This is a total nit pick, but these are a biiiit too short. I only notice it in the dock. Understand if this is a won't fix 😆 

Compared to Apple:

<img width="173" alt="Screenshot 2024-05-18 at 11 59 30 AM" src="https://github.com/jasonlong/iterm2-icons/assets/848343/cc566e1c-1926-48b8-be7c-9c6369e8ca6b">

See 1px line above icon:

<img width="191" alt="Screenshot 2024-05-18 at 12 00 50 PM" src="https://github.com/jasonlong/iterm2-icons/assets/848343/0838080a-b131-4337-b760-1ea1044e8ff0">

Compared to other 3rd party

<img width="173" alt="Screenshot 2024-05-18 at 11 56 57 AM" src="https://github.com/jasonlong/iterm2-icons/assets/848343/5fbfd02d-5bd1-4938-a852-baea5b217d31">

**Comment by jasonlong** [comment]
Hey @scosman - great eye noticing this. I've been using [Ghostty](https://github.com/mitchellh/ghostty) lately (which has a great icon already) and haven't used these icons for a while. Given that, I probably won't get around to making any further tweaks in this repo.
